import { Camera, Wifi, Monitor, Shield, Network, Server, Cpu, Home, Building2, Warehouse, Lock, Bell, Phone, Cable, Radio, Settings, Wrench, HardDrive, Printer, LifeBuoy, FileCheck, Zap } from 'lucide-react';

export const BUSINESS = {
  name: 'AR IT Solutions',
  tagline: 'Professional CCTV Installation • Networking • Security Solutions',
  phone: '+91 9392815526',
  whatsapp: '+919392815526',
  email: 'info@aritsolutions.in',
  address: 'Jagadgirigutta, Kukatpally, Hyderabad, Telangana 500072, India',
  hours: 'Monday – Saturday | 9:00 AM – 8:00 PM',
  mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3806.1234567890!2d78.3980!3d17.5100!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sJagadgirigutta%2C+Kukatpally%2C+Hyderabad!5e0!3m2!1sen!2sin!4v1700000000000',
};

export const SERVICES = [
  {
    id: 'cctv-installation',
    icon: Camera,
    category: 'cctv',
    title: 'CCTV Camera Installation',
    shortDesc: 'Professional installation of high-definition surveillance cameras for complete property protection.',
    description: 'Our expert technicians provide end-to-end CCTV installation services tailored to your specific security needs. We handle everything from site survey to commissioning, ensuring optimal camera placement for maximum coverage.',
    features: ['Site survey & consultation', 'Professional mounting & cabling', 'DVR/NVR configuration', 'Remote viewing setup', 'Night vision cameras', 'Motion detection alerts'],
    benefits: ['24/7 property monitoring', 'Crime deterrence', 'Evidence recording', 'Remote access via mobile', 'Insurance benefits'],
    industries: ['Residential', 'Commercial', 'Industrial', 'Educational', 'Healthcare'],
    image: 'https://images.pexels.com/photos/3205386/pexels-photo-3205386.jpeg',
  },
  {
    id: 'ip-cctv',
    icon: Monitor,
    category: 'cctv',
    title: 'IP CCTV Cameras',
    shortDesc: 'High-resolution IP camera systems with advanced analytics and remote monitoring capabilities.',
    description: 'IP cameras deliver superior image quality and advanced features including facial recognition, license plate capture, and AI-powered analytics for intelligent surveillance.',
    features: ['4K Ultra HD resolution', 'AI-powered analytics', 'PoE technology', 'H.265+ compression', 'Cloud storage option', 'Two-way audio'],
    benefits: ['Crystal-clear footage', 'Smart detection alerts', 'Scalable system', 'Network integration', 'Future-proof technology'],
    industries: ['Corporate', 'Retail', 'Hospitality', 'Banking', 'Healthcare'],
    image: 'https://images.pexels.com/photos/3205384/pexels-photo-3205384.jpeg',
  },
  {
    id: 'hd-cctv',
    icon: Camera,
    category: 'cctv',
    title: 'HD CCTV Systems',
    shortDesc: 'Crystal-clear HD surveillance with 1080p to 8MP resolution for superior identification.',
    description: 'High-definition CCTV systems provide sharp, detailed footage essential for identifying faces, reading number plates, and gathering evidence. Perfect for businesses requiring reliable surveillance.',
    features: ['1080p to 8MP resolution', 'TVI/AHD/CVI technology', 'Long-range night vision', 'Wide dynamic range', 'Vandal-proof housing', 'IP66 weatherproofing'],
    benefits: ['Clear identification footage', 'Cost-effective solution', 'Easy upgrade path', 'Reliable performance', 'Wide compatibility'],
    industries: ['SMEs', 'Shops', 'Offices', 'Apartments', 'Warehouses'],
    image: 'https://images.pexels.com/photos/3205387/pexels-photo-3205387.jpeg',
  },
  {
    id: 'wireless-cctv',
    icon: Wifi,
    category: 'cctv',
    title: 'Wireless CCTV Solutions',
    shortDesc: 'Cable-free surveillance systems ideal for locations where wiring is impractical.',
    description: 'Our wireless CCTV solutions eliminate the need for extensive cabling, making them perfect for rental properties, heritage buildings, and locations requiring flexible installation.',
    features: ['No cabling required', 'Battery-powered options', 'WiFi & 4G connectivity', 'Solar-powered variants', 'Easy relocation', 'Cloud-based storage'],
    benefits: ['Minimal installation disruption', 'Flexible placement', 'Quick setup', 'Ideal for rentals', 'Eco-friendly options'],
    industries: ['Rental Properties', 'Construction Sites', 'Remote Locations', 'Heritage Buildings'],
    image: 'https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg',
  },
  {
    id: 'home-security',
    icon: Home,
    category: 'cctv',
    title: 'Home Security Systems',
    shortDesc: 'Complete home protection with cameras, alarms, and smart monitoring for peace of mind.',
    description: 'Protect your family and belongings with our comprehensive home security solutions. From doorbell cameras to complete multi-camera systems, we design security tailored to your home.',
    features: ['Doorbell cameras', 'Indoor & outdoor cameras', 'Motion-activated alerts', 'Smartphone app control', 'Professional monitoring', 'Smart home integration'],
    benefits: ['Family safety', 'Property protection', 'Real-time alerts', 'Insurance discounts', 'Peace of mind'],
    industries: ['Villas', 'Apartments', 'Independent Houses', 'Gated Communities'],
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg',
  },
  {
    id: 'office-surveillance',
    icon: Building2,
    category: 'cctv',
    title: 'Office Surveillance Systems',
    shortDesc: 'Comprehensive office security with employee monitoring, access control integration.',
    description: 'Keep your workplace safe, productive, and secure with professional office surveillance systems. Monitor common areas, entrances, server rooms, and sensitive zones effectively.',
    features: ['Entrance & lobby coverage', 'Server room monitoring', 'Conference room cameras', 'Access control integration', 'Employee safety compliance', 'Centralized management'],
    benefits: ['Theft prevention', 'Employee productivity', 'Compliance documentation', 'Incident investigation', 'Visitor management'],
    industries: ['Corporate Offices', 'IT Companies', 'Law Firms', 'Financial Services'],
    image: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg',
  },
  {
    id: 'apartment-cctv',
    icon: Building2,
    category: 'cctv',
    title: 'Apartment CCTV Solutions',
    shortDesc: 'Multi-unit residential surveillance covering lobbies, parking, and common areas.',
    description: 'Comprehensive CCTV solutions for apartment complexes and residential societies. We design systems that cover all common areas while respecting resident privacy.',
    features: ['Lobby & entrance monitoring', 'Parking area coverage', 'Lift surveillance', 'Perimeter security', 'Centralized monitoring', 'Society management integration'],
    benefits: ['Enhanced resident safety', 'Visitor tracking', 'Parking management', 'Evidence for disputes', 'Property value increase'],
    industries: ['Apartments', 'Residential Societies', 'Gated Communities', 'Housing Colonies'],
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg',
  },
  {
    id: 'warehouse-security',
    icon: Warehouse,
    category: 'cctv',
    title: 'Warehouse Security Systems',
    shortDesc: 'Industrial-grade surveillance for warehouses, factories, and large-scale facilities.',
    description: 'Protect valuable inventory and ensure operational safety in large warehouse and industrial environments. Our systems cover vast areas with pan-tilt-zoom and wide-angle cameras.',
    features: ['Wide-area coverage cameras', 'PTZ cameras', 'Loading dock monitoring', 'Perimeter protection', 'After-hours alert system', 'Integration with access control'],
    benefits: ['Inventory protection', 'Safety compliance', 'Operational visibility', 'Theft prevention', 'Insurance support'],
    industries: ['Warehouses', 'Manufacturing', 'Logistics', 'Cold Storage', 'Distribution Centers'],
    image: 'https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg',
  },
  {
    id: 'biometric',
    icon: Lock,
    category: 'access',
    title: 'Biometric Attendance Systems',
    shortDesc: 'Fingerprint and face recognition systems for accurate employee attendance tracking.',
    description: 'Modern biometric systems eliminate buddy punching and ensure accurate attendance records. Our solutions integrate with payroll software for seamless HR management.',
    features: ['Fingerprint recognition', 'Face recognition', 'RFID card support', 'Payroll integration', 'Real-time reports', 'Cloud-based management'],
    benefits: ['Accurate attendance', 'No proxy attendance', 'Automated payroll', 'Real-time monitoring', 'Cost savings'],
    industries: ['Factories', 'Offices', 'Schools', 'Hospitals', 'Government'],
    image: 'https://images.pexels.com/photos/8721342/pexels-photo-8721342.jpeg',
  },
  {
    id: 'access-control',
    icon: Shield,
    category: 'access',
    title: 'Access Control Systems',
    shortDesc: 'Restrict and monitor entry to sensitive areas with smart access control solutions.',
    description: 'Control who enters specific areas of your premises with our advanced access control systems. From simple keycard readers to multi-factor authentication, we have solutions for every need.',
    features: ['RFID card readers', 'Biometric access', 'PIN-based entry', 'Multi-zone control', 'Audit trail logs', 'Time-based restrictions'],
    benefits: ['Restricted area protection', 'Complete audit trails', 'Scalable security', 'Eliminate key management', 'Emergency lockdown'],
    industries: ['Data Centers', 'Laboratories', 'Hospitals', 'Corporate', 'Government'],
    image: 'https://images.pexels.com/photos/279810/pexels-photo-279810.jpeg',
  },
  {
    id: 'video-door-phone',
    icon: Bell,
    category: 'access',
    title: 'Video Door Phones',
    shortDesc: 'See and speak with visitors before granting entry with HD video door phone systems.',
    description: 'Video door phones add an essential layer of security at your entrance. See, speak, and control door access from anywhere using your smartphone with our smart video door phone systems.',
    features: ['HD video quality', 'Two-way audio', 'Night vision', 'Smartphone connectivity', 'Multi-unit expansion', 'Cloud video history'],
    benefits: ['Visitor verification', 'Remote door control', 'Enhanced safety', 'Package delivery management', 'Peace of mind'],
    industries: ['Homes', 'Apartments', 'Offices', 'Commercial', 'Banks'],
    image: 'https://images.pexels.com/photos/3990359/pexels-photo-3990359.jpeg',
  },
  {
    id: 'intercom',
    icon: Phone,
    category: 'access',
    title: 'Intercom Systems',
    shortDesc: 'Internal communication systems for offices, hospitals, and residential complexes.',
    description: 'Modern intercom systems facilitate seamless internal communication across floors, departments, and buildings. From basic audio intercoms to full IP-based video systems.',
    features: ['Audio & video options', 'Multi-unit systems', 'IP-based connectivity', 'Master station control', 'Integration capability', 'Crystal-clear audio'],
    benefits: ['Improved communication', 'Enhanced security', 'Cost efficiency', 'Visitor management', 'Emergency response'],
    industries: ['Offices', 'Hospitals', 'Schools', 'Apartments', 'Industrial'],
    image: 'https://images.pexels.com/photos/8721342/pexels-photo-8721342.jpeg',
  },
  {
    id: 'network-cabling',
    icon: Cable,
    category: 'networking',
    title: 'Network Cabling',
    shortDesc: 'Professional data cabling installation for reliable, high-speed network infrastructure.',
    description: 'Build a solid network foundation with our professional cabling services. We install Cat5e, Cat6, and Cat6A cables following industry standards for maximum performance and longevity.',
    features: ['Cat5e/Cat6/Cat6A cabling', 'TIA-568 standards compliance', 'Proper cable management', 'Labeling & documentation', 'Testing & certification', 'Warranty coverage'],
    benefits: ['High-speed connectivity', 'Reliable performance', 'Future-proof infrastructure', 'Easy troubleshooting', 'Professional documentation'],
    industries: ['Offices', 'Data Centers', 'Educational', 'Healthcare', 'Retail'],
    image: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg',
  },
  {
    id: 'structured-cabling',
    icon: Network,
    category: 'networking',
    title: 'Structured Cabling',
    shortDesc: 'Comprehensive structured cabling infrastructure for enterprise-grade networks.',
    description: 'Structured cabling provides a standardized, scalable telecommunications infrastructure that supports multiple hardware uses. Our certified engineers design and install systems to TIA/EIA standards.',
    features: ['TIA/EIA standards', 'Horizontal & backbone cabling', 'Telecommunications rooms', 'Equipment rooms', 'Cable tray systems', 'Complete documentation'],
    benefits: ['Standardized infrastructure', 'Easy management', 'Future scalability', 'Reduced downtime', 'Professional compliance'],
    industries: ['Large Enterprises', 'Data Centers', 'Campus Networks', 'Industrial', 'Government'],
    image: 'https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg',
  },
  {
    id: 'lan-setup',
    icon: Network,
    category: 'networking',
    title: 'LAN Setup',
    shortDesc: 'Complete local area network design and installation for offices and businesses.',
    description: 'A well-designed LAN is the backbone of your business operations. We design, install, and configure local area networks that deliver fast, reliable connectivity to every workstation.',
    features: ['Network design & planning', 'Switch & router setup', 'VLAN configuration', 'QoS implementation', 'Network security setup', 'Documentation'],
    benefits: ['Fast internal communication', 'Resource sharing', 'Centralized management', 'Secure segmentation', 'Scalable design'],
    industries: ['SMEs', 'Offices', 'Schools', 'Shops', 'Medical Clinics'],
    image: 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg',
  },
  {
    id: 'wifi-installation',
    icon: Wifi,
    category: 'networking',
    title: 'WiFi Installation',
    shortDesc: 'Enterprise-grade wireless networks with full coverage and zero dead zones.',
    description: 'Professional WiFi installation using enterprise-grade access points ensures seamless wireless coverage throughout your premises. We conduct site surveys and design optimal access point placement.',
    features: ['Site survey', 'Enterprise access points', 'Seamless roaming', 'Dual-band & tri-band', 'Guest network isolation', 'Bandwidth management'],
    benefits: ['Complete coverage', 'High-speed wireless', 'Multiple device support', 'Secure access', 'Professional management'],
    industries: ['Hotels', 'Restaurants', 'Offices', 'Schools', 'Retail', 'Healthcare'],
    image: 'https://images.pexels.com/photos/1181311/pexels-photo-1181311.jpeg',
  },
  {
    id: 'mesh-wifi',
    icon: Radio,
    category: 'networking',
    title: 'Mesh WiFi Setup',
    shortDesc: 'Whole-home and office mesh WiFi for seamless multi-room wireless coverage.',
    description: 'Mesh WiFi systems use multiple nodes to create a single unified wireless network, eliminating dead zones and providing consistent speed throughout large or multi-story spaces.',
    features: ['Multi-node mesh system', 'Self-healing network', 'Automatic failover', 'Seamless band switching', 'App-based management', 'Parental controls'],
    benefits: ['Zero dead zones', 'Consistent speeds', 'Easy management', 'Self-optimizing', 'Scalable coverage'],
    industries: ['Large Homes', 'Multi-floor Offices', 'Hotels', 'Restaurants', 'Showrooms'],
    image: 'https://images.pexels.com/photos/4219863/pexels-photo-4219863.jpeg',
  },
  {
    id: 'fiber-optic',
    icon: Cable,
    category: 'networking',
    title: 'Fiber Optic Cabling',
    shortDesc: 'High-speed fiber optic installation for gigabit-capable enterprise networks.',
    description: 'Fiber optic cabling delivers unmatched speed, bandwidth, and distance capabilities for demanding enterprise environments. We install single-mode and multi-mode fiber for backbone and premises applications.',
    features: ['Single & multi-mode fiber', 'Fusion splicing', 'OTDR testing', 'SC, LC, ST connectors', 'Armored cable options', 'Complete certification'],
    benefits: ['Gigabit+ speeds', 'Long-distance capability', 'EMI immunity', 'Future bandwidth', 'Secure transmission'],
    industries: ['Data Centers', 'Campus Networks', 'ISPs', 'Industrial', 'Healthcare'],
    image: 'https://images.pexels.com/photos/159304/network-cable-ethernet-computer-159304.jpeg',
  },
  {
    id: 'server-rack',
    icon: Server,
    category: 'networking',
    title: 'Server Rack Installation',
    shortDesc: 'Professional server rack setup and cable management for clean, organized IT infrastructure.',
    description: 'Proper server rack installation ensures your IT infrastructure is organized, accessible, and operating efficiently. We handle rack placement, cable management, and power distribution.',
    features: ['Rack assembly & mounting', 'Cable management', 'Power distribution units', 'Patch panel installation', 'Cooling optimization', 'Asset labeling'],
    benefits: ['Organized infrastructure', 'Easy maintenance', 'Optimal airflow', 'Reduced downtime', 'Professional appearance'],
    industries: ['Data Centers', 'Offices', 'Telecom', 'Broadcasting', 'Educational'],
    image: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg',
  },
  {
    id: 'computer-repair',
    icon: Cpu,
    category: 'it-support',
    title: 'Computer Repair',
    shortDesc: 'Expert desktop and workstation repair, upgrades, and maintenance services.',
    description: 'Fast and reliable computer repair services for all brands and models. From hardware failures to software issues, virus removal to performance optimization, we fix it all.',
    features: ['Hardware diagnostics', 'Motherboard repairs', 'Data recovery', 'Virus removal', 'OS reinstallation', 'Upgrades & optimization'],
    benefits: ['Fast turnaround', 'Expert diagnosis', 'Data safety', 'Cost-effective', 'Warranty on repairs'],
    industries: ['Individuals', 'Small Businesses', 'Schools', 'Offices', 'Healthcare'],
    image: 'https://images.pexels.com/photos/1181248/pexels-photo-1181248.jpeg',
  },
  {
    id: 'laptop-repair',
    icon: Monitor,
    category: 'it-support',
    title: 'Laptop Repair',
    shortDesc: 'Comprehensive laptop repair for all brands — screen, keyboard, motherboard, and more.',
    description: 'Our technicians are trained to repair all major laptop brands. Whether it\'s a broken screen, faulty keyboard, water damage, or battery replacement, we provide fast and reliable repairs.',
    features: ['Screen replacement', 'Keyboard repairs', 'Battery replacement', 'Motherboard repair', 'Data recovery', 'Water damage treatment'],
    benefits: ['All brands serviced', 'Quick repairs', 'Original parts', 'Competitive pricing', 'Pickup & delivery'],
    industries: ['Students', 'Professionals', 'Businesses', 'Schools', 'Remote Workers'],
    image: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg',
  },
  {
    id: 'printer-installation',
    icon: Printer,
    category: 'it-support',
    title: 'Printer Installation',
    shortDesc: 'Setup and configuration of printers, scanners, and multifunction devices for offices.',
    description: 'We provide professional printer installation and configuration services for all types of printers. Including network printer setup, driver installation, and troubleshooting.',
    features: ['All printer brands', 'Network printer setup', 'Driver installation', 'Print server config', 'WiFi printing setup', 'Maintenance & repair'],
    benefits: ['Quick installation', 'Network accessibility', 'Optimal print quality', 'Reduced support calls', 'Proactive maintenance'],
    industries: ['Offices', 'Schools', 'Print Shops', 'Healthcare', 'Retail'],
    image: 'https://images.pexels.com/photos/4792729/pexels-photo-4792729.jpeg',
  },
  {
    id: 'remote-support',
    icon: LifeBuoy,
    category: 'it-support',
    title: 'Remote IT Support',
    shortDesc: 'Instant remote support for software issues, configurations, and IT troubleshooting.',
    description: 'Our remote support team can resolve most IT issues without a site visit, saving you time and money. Connect with our experts in minutes for fast problem resolution.',
    features: ['Instant connectivity', 'Software troubleshooting', 'Configuration support', 'Security updates', 'Performance optimization', 'Guidance & training'],
    benefits: ['No waiting for technician', 'Cost-effective', 'Immediate resolution', 'Available 6 days a week', 'Comprehensive logging'],
    industries: ['SMEs', 'Remote Workers', 'Schools', 'Healthcare', 'Retail'],
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
  },
  {
    id: 'amc',
    icon: FileCheck,
    category: 'it-support',
    title: 'Annual Maintenance Contract',
    shortDesc: 'Comprehensive AMC plans ensuring optimal performance of all your IT and security systems.',
    description: 'Our Annual Maintenance Contracts provide peace of mind with scheduled maintenance, priority support, and proactive monitoring of all your CCTV, networking, and IT systems.',
    features: ['Scheduled maintenance visits', 'Priority response', 'Preventive checks', 'System health reports', 'Emergency support', 'Spare parts coverage'],
    benefits: ['System longevity', 'Cost predictability', 'Priority service', 'Minimal downtime', 'Expert oversight'],
    industries: ['Offices', 'Apartments', 'Schools', 'Hospitals', 'Hotels', 'Retail'],
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg',
  },
  {
    id: 'smart-home',
    icon: Zap,
    category: 'smart',
    title: 'Smart Home Automation',
    shortDesc: 'Transform your home with intelligent automation for lighting, security, and comfort.',
    description: 'Make your home smarter and more efficient with our home automation solutions. Control lighting, fans, ACs, security cameras, and door locks from your smartphone or voice commands.',
    features: ['Smart lighting control', 'Climate automation', 'Security integration', 'Voice control (Alexa/Google)', 'Scene customization', 'Energy monitoring'],
    benefits: ['Energy savings', 'Convenience', 'Enhanced security', 'Increased property value', 'Modern lifestyle'],
    industries: ['Villas', 'Luxury Apartments', 'Smart Offices', 'Hotels', 'Showrooms'],
    image: 'https://images.pexels.com/photos/3990359/pexels-photo-3990359.jpeg',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Services' },
  { id: 'cctv', label: 'CCTV & Surveillance' },
  { id: 'access', label: 'Access Control' },
  { id: 'networking', label: 'Networking' },
  { id: 'it-support', label: 'IT Support' },
  { id: 'smart', label: 'Smart Solutions' },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    role: 'Business Owner',
    company: 'Kukatpally Electronics',
    review: 'AR IT Solutions installed CCTV cameras across my three shops. The work was professional, neat, and the remote viewing works perfectly. Highly recommend their services!',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Apartment Secretary',
    company: 'Green Valley Apartments',
    review: 'We hired AR IT Solutions for our entire apartment complex. They covered all 8 floors, parking, and lobby. Excellent team, transparent pricing, and superb after-sales support.',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
  },
  {
    id: 3,
    name: 'Mohammed Farooq',
    role: 'IT Manager',
    company: 'TechPark Solutions',
    review: 'The structured cabling and server rack installation by AR IT Solutions transformed our office network. Zero downtime, perfectly organized, and certified testing done professionally.',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg',
  },
  {
    id: 4,
    name: 'Sunita Reddy',
    role: 'Principal',
    company: 'Bright Future School',
    review: 'From biometric attendance to WiFi network for our entire campus — AR IT Solutions delivered everything on time and within budget. Their AMC plan keeps everything running perfectly.',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    id: 5,
    name: 'Venkat Rao',
    role: 'Warehouse Manager',
    company: 'Hyderabad Logistics Hub',
    review: 'We needed heavy-duty security for our 50,000 sq ft warehouse. AR IT Solutions designed a comprehensive system with PTZ cameras and perimeter protection. Outstanding work!',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg',
  },
  {
    id: 6,
    name: 'Anitha Menon',
    role: 'Homeowner',
    company: 'Jagadgirigutta',
    review: 'Installed smart home automation and security cameras for my villa. The team was courteous, clean in their work, and explained everything clearly. Best decision I made!',
    rating: 5,
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
  },
];

export const PORTFOLIO = [
  {
    id: 1,
    title: '16-Camera Office Surveillance System',
    category: 'cctv',
    location: 'Kukatpally, Hyderabad',
    description: 'Complete IP camera system with centralized NVR monitoring and mobile access.',
    image: 'https://images.pexels.com/photos/3205386/pexels-photo-3205386.jpeg',
    tags: ['IP Cameras', 'NVR', 'Remote Viewing'],
  },
  {
    id: 2,
    title: 'Apartment Complex Security Setup',
    category: 'cctv',
    location: 'Miyapur, Hyderabad',
    description: '32-camera surveillance system covering all common areas and parking.',
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg',
    tags: ['HD CCTV', 'Apartment', 'Parking Surveillance'],
  },
  {
    id: 3,
    title: 'Enterprise WiFi Network Deployment',
    category: 'networking',
    location: 'HITEC City, Hyderabad',
    description: 'Enterprise-grade WiFi with 24 access points covering 15,000 sq ft office.',
    image: 'https://images.pexels.com/photos/1181311/pexels-photo-1181311.jpeg',
    tags: ['WiFi', 'Enterprise', 'Network'],
  },
  {
    id: 4,
    title: 'School Biometric & Access Control',
    category: 'access',
    location: 'JNTU, Hyderabad',
    description: 'Multi-point biometric attendance system for 1,200 students and 80 staff.',
    image: 'https://images.pexels.com/photos/8721342/pexels-photo-8721342.jpeg',
    tags: ['Biometric', 'Access Control', 'School'],
  },
  {
    id: 5,
    title: 'Warehouse Security System',
    category: 'cctv',
    location: 'Balanagar, Hyderabad',
    description: 'Industrial CCTV with PTZ cameras and 24/7 perimeter protection.',
    image: 'https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg',
    tags: ['PTZ Cameras', 'Warehouse', 'Industrial'],
  },
  {
    id: 6,
    title: 'Server Room Infrastructure',
    category: 'networking',
    location: 'Madhapur, Hyderabad',
    description: 'Complete server rack installation with structured cabling and cooling.',
    image: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg',
    tags: ['Server Rack', 'Structured Cabling', 'Data Center'],
  },
  {
    id: 7,
    title: 'Smart Villa Automation',
    category: 'smart',
    location: 'Kompally, Hyderabad',
    description: 'Complete smart home setup with lighting, security, and climate control.',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg',
    tags: ['Smart Home', 'Automation', 'Villa'],
  },
  {
    id: 8,
    title: 'Hospital Surveillance Network',
    category: 'cctv',
    location: 'Secunderabad, Hyderabad',
    description: '48-camera network with ANPR at entrance and patient area monitoring.',
    image: 'https://images.pexels.com/photos/3205384/pexels-photo-3205384.jpeg',
    tags: ['Healthcare', 'ANPR', 'IP Network'],
  },
];

export const FAQS = [
  {
    q: 'How many cameras do I need for my home?',
    a: 'For a typical home, we recommend 4–8 cameras covering main entrance, back door, driveway, and key interior areas. A site survey helps determine the exact number based on your property layout.',
  },
  {
    q: 'What is the difference between DVR and NVR?',
    a: 'DVR (Digital Video Recorder) works with analog/HD-TVI cameras, while NVR (Network Video Recorder) works with IP cameras. NVR systems generally offer higher resolution, better scalability, and advanced features like analytics.',
  },
  {
    q: 'Can I view my CCTV cameras on my smartphone?',
    a: 'Yes! All our CCTV systems support remote viewing through mobile apps. You can view live footage, playback recordings, and receive motion alerts on your Android or iOS device from anywhere in the world.',
  },
  {
    q: 'How long is footage stored in the CCTV system?',
    a: 'Storage duration depends on the hard drive size, number of cameras, and recording quality. Typically 7–30 days with a 2TB–8TB HDD. We calculate the exact storage needed during the site survey.',
  },
  {
    q: 'What is the warranty on installed systems?',
    a: 'We provide a 1-year warranty on all installed systems covering both hardware and labor. Extended warranties and AMC plans are available for ongoing support and maintenance.',
  },
  {
    q: 'Do you provide service after installation?',
    a: 'Yes, we offer comprehensive after-sales support. You can call, WhatsApp, or email us for any issues. We also offer Annual Maintenance Contracts (AMC) for priority support and scheduled preventive maintenance.',
  },
  {
    q: 'How long does a typical CCTV installation take?',
    a: 'A home installation of 4–8 cameras typically takes one day. Larger commercial or industrial projects may require 2–7 days depending on scope. We provide a timeline estimate during the site survey.',
  },
  {
    q: 'Do you install cameras in rented premises?',
    a: 'Yes, we can install cameras in rented properties with the landlord\'s permission. Wireless options are available for minimal structural changes. We ensure easy removal when needed.',
  },
  {
    q: 'What type of network cabling do you use?',
    a: 'We primarily use Cat6 cabling which supports Gigabit speeds up to 100 meters. For demanding environments or future-proofing, we offer Cat6A (10 Gigabit) and fiber optic installations.',
  },
  {
    q: 'Do you offer a free site survey?',
    a: 'Yes! We provide a free site survey and consultation for all projects. Our expert will visit, assess your requirements, and provide a detailed quotation with no obligation.',
  },
];

export const PRICING_PLANS = [
  {
    id: 'basic',
    name: 'Home Starter',
    price: '8,999',
    period: 'onwards',
    description: 'Perfect for small homes and apartments requiring basic security coverage.',
    features: [
      '4 HD CCTV Cameras (2MP)',
      '1 TB DVR / 4 Channel',
      'Night Vision up to 20m',
      'Mobile Viewing App',
      'Professional Installation',
      '1 Year Warranty',
      '24/7 WhatsApp Support',
    ],
    notIncluded: ['Remote monitoring', 'Advanced analytics', 'AMC contract'],
    highlight: false,
    badge: '',
  },
  {
    id: 'professional',
    name: 'Business Pro',
    price: '24,999',
    period: 'onwards',
    description: 'Ideal for offices, shops, and commercial establishments requiring comprehensive coverage.',
    features: [
      '8 IP CCTV Cameras (4MP)',
      '2 TB NVR / 8 Channel',
      'AI Motion Detection',
      'Night Vision up to 40m',
      'Mobile & Web Viewing',
      'Professional Installation',
      '1 Year Warranty',
      'On-site Support (48hrs)',
      'Basic Access Control',
    ],
    notIncluded: ['AMC contract', 'Server rack setup'],
    highlight: true,
    badge: 'Most Popular',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    period: 'quote',
    description: 'Tailored solutions for large commercial, industrial, and enterprise environments.',
    features: [
      'Unlimited IP Cameras (4K)',
      'Enterprise NVR/DVR',
      'Advanced AI Analytics',
      'Perimeter Protection',
      'Biometric Access Control',
      'Fiber Optic Network',
      'Server Rack Setup',
      '24/7 Monitoring',
      'Priority AMC Support',
      'Custom Integrations',
    ],
    notIncluded: [],
    highlight: false,
    badge: 'Custom',
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'How to Choose the Right CCTV Camera for Your Home in 2025',
    slug: 'choose-right-cctv-camera-home-2025',
    excerpt: 'With so many CCTV options available, choosing the right camera can be overwhelming. This guide breaks down the key factors to consider for optimal home security.',
    category: 'CCTV',
    date: 'November 15, 2024',
    readTime: '5 min read',
    image: 'https://images.pexels.com/photos/3205386/pexels-photo-3205386.jpeg',
    author: 'AR IT Team',
  },
  {
    id: 2,
    title: 'WiFi vs Wired Network: What\'s Best for Your Office?',
    slug: 'wifi-vs-wired-network-office',
    excerpt: 'Deciding between a wired LAN and wireless WiFi network for your office? We compare performance, security, cost, and reliability to help you make the right choice.',
    category: 'Networking',
    date: 'October 28, 2024',
    readTime: '6 min read',
    image: 'https://images.pexels.com/photos/1181311/pexels-photo-1181311.jpeg',
    author: 'AR IT Team',
  },
  {
    id: 3,
    title: 'Top 5 Benefits of Biometric Attendance for Small Businesses',
    slug: 'benefits-biometric-attendance-small-businesses',
    excerpt: 'Biometric attendance systems are no longer just for large corporations. Discover how fingerprint and face recognition can transform attendance management for SMEs.',
    category: 'Access Control',
    date: 'October 10, 2024',
    readTime: '4 min read',
    image: 'https://images.pexels.com/photos/8721342/pexels-photo-8721342.jpeg',
    author: 'AR IT Team',
  },
];

export const STATS = [
  { label: 'Projects Completed', value: 1500, suffix: '+' },
  { label: 'Happy Clients', value: 1200, suffix: '+' },
  { label: 'Years Experience', value: 8, suffix: '+' },
  { label: 'Expert Technicians', value: 15, suffix: '+' },
];

export const PROCESS_STEPS = [
  {
    step: '01',
    title: 'Free Site Survey',
    description: 'Our expert visits your site, assesses your security needs, and identifies optimal camera placement and infrastructure requirements.',
    icon: 'search',
  },
  {
    step: '02',
    title: 'Custom Proposal',
    description: 'We prepare a detailed, transparent quotation with equipment specifications, timeline, and pricing — no hidden charges.',
    icon: 'file-text',
  },
  {
    step: '03',
    title: 'Professional Installation',
    description: 'Certified technicians install all equipment neatly and professionally, minimizing disruption to your daily operations.',
    icon: 'tool',
  },
  {
    step: '04',
    title: 'Testing & Handover',
    description: 'Full system testing, configuration of remote access, and complete training so you can operate your system confidently.',
    icon: 'check-circle',
  },
];
